  navbar:
    background: dark
    left:
      - text: "Home"
        href: ../../../index.html
      - text: Github
        href: https://github.com/TheNudibranch
      - text: LinkedIn
        href: https://www.linkedin.com/in/ian-s-costley/
      - text: Blog
        href: ../../blog.html